version: "3.9"

networks:
  ollama:


services:

  open-webui:
    image: docker.io/backplane/open-webui:0.3.10
    volumes:
      - /mnt/wsl/instances/Ubuntu/ollama-docker/data/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3002:8080
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama

  pipelines:
    image: localhost/open-webui/pipelines:latest
    volumes:
      - /mnt/wsl/instances/Ubuntu/ollama-docker/data/pipelines:/app/pipelines
    depends_on:
      - ollama
    ports:
      - 39099:9099
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    networks:
      - ollama
    volumes:
      - /mnt/wsl/instances/Ubuntu/ollama-docker/data/ollama/config/litellm:/app
    command:
      [
        "--config",
        "/app/config.yaml",
        "--port",
        "8000",
        "--num_workers",
        "8"
      ]
    depends_on:
      - ollama
      - redis
    ports:
      - 8000:8000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: SDsdgFsfm4lmf43lfnm34lkf

  ollama:
    image: ollama/ollama
    networks:
      - ollama
    volumes:
      - /mnt/wsl/instances/Ubuntu/ollama-docker/data/ollama:/root/.ollama
    ports:
      - 11434:11434

  redis:
    image: redis:7-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    environment:
      REDIS_PASSWORD: SDsdgFsfm4lmf43lfnm34lkf
    volumes:
      - /mnt/wsl/instances/Ubuntu/ollama-docker/data/redis:/data
    networks:
      - ollama
